[workspace]
members = [
    "crates/QcCore",
    "crates/QcGame",
    "crates/QcTools",
    "crates/QcWindowing",
    "crates/QcUI",
    "crates/QcRender",
    "crates/QcMacros",
    "crates/QcExport",
    "crates/QcScript"
]

